pipeline {
    agent any

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        
        stage('Print Hello World') {
            steps {
                echo 'Hello World'
            }
        }

        stage('Run Python Script') {
            steps {
                script {
                    // בדיקת גרסת Python
                    bat 'python --version'
                    // הרצת הסקריפט Python
                    bat 'python pythonJenkins.py
                }
            }
        }
    }
}
