pipeline {
    agent any

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        
        stage('Print Hello World') {
            steps {
                echo 'Hello World'
            }
        }
        
        stage('Run Python Script') {
            steps {
                dir('Jenkins') {
                    script {
                        // הרצת Python מתוך תיקיית Jenkins
                        bat 'pythonJenkins.py'
                    }
                }
            }
        }
    }
}

